const api = {
  bookingTypes: "https://taxitriptypebackend-microservices.api.lagosride.com",
  // classTypes: 'https://134.209.16.20:7090',
  classTypes: "https://taxiclasstypebackend-microservices.api.lagosride.com",
  user: "https://users-service-microservices.api.lagosride.com",
  fees: "https://fees-service-microservices.api.lagosride.com",
  area: "https://area-service-microservices.api.lagosride.com",
  promo: "https://taxipromobackend-microservices.api.lagosride.com",
  vehicles: "https://vehicle-service-microservices.api.lagosride.com",
  admins: "https://taxiadminbackend-microservices.api.lagosride.com",
  ticket: "https://taxiticketbackend-microservices.api.lagosride.com",
  support: "https://support-service-microservices.api.lagosride.com",
  rating: "https://triprating-service-microservices.api.lagosride.com",
  fdt: "https://fdt-service-microservices.api.lagosride.com",
  trip: "https://tripreporting-service-microservices.api.lagosride.com",
  sos: "https://sos-service-microservices.api.lagosride.com",
  // revenueSplit: 'https://taxirevenuesplitbackend-microservices.api.lagosride.com',
  cancellationReasons: "https://tripcancel-reasons-microservices.api.lagosride.com",
  customerCare: "https://settings-service-microservices.api.lagosride.com",
  referral: "https://referral-service-microservices.api.lagosride.com",
  messageWorker: "https://message-service-microservices.api.lagosride.com",
  wallet: "https://wallet-service-microservices.api.lagosride.com",
  contactUs: "https://contact-us-microservices.api.lagosride.com",
  revenueSplit: "https://revenue-service-microservices.api.lagosride.com",
  idVerification: "https://verify-service-microservices.api.lagosride.com",
};

export default api;
