export const lgaList = [
  {label: "Agbado/Oke-Odo", value: "Agbado/Oke-Odo"},
  {label: "Agboyi/Ketu", value: "Agboyi/Ketu"},
  {label: "Agege", value: "Agege"},
  {label: "Ajeromi Ifelodun", value: "Ajeromi Ifelodun"},
  {label: "Alimosho", value: "Alimosho"},
  {label: "Amuwo Odofin", value: "Amuwo Odofin"},
  {label: "Apapa", value: "Apapa"},
  {label: "Apapa Iganmu", value: "Apapa Iganmu"},
  {label: "Ayobo-Ipaja", value: "Ayobo-Ipaja"},
  {label: "Badagry", value: "Badagry"},
  {label: "Badagry West", value: "Badagry West"},
  {label: "Bariga", value: "Bariga"},
  {label: "Coker/Aguda", value: "Coker/Aguda"},
  {label: "Egbe/Idimu", value: "Egbe/Idimu"},
  {label: "Ejigbo", value: "Ejigbo"},
  {label: "Epe", value: "Epe"},
  {label: "Eredo", value: "Eredo"},
  {label: "Eti-Osa", value: "Eti-Osa"},
  {label: "Eti-Osa East", value: "Eti-Osa East"},
  {label: "Iba", value: "Iba"},
  {label: "Ibeju/Lekki", value: "Ibeju/Lekki"},
  {label: "Ifako/Ijaiye", value: "Ifako/Ijaiye"},
  {label: "Ifelodun", value: "Ifelodun"},
  {label: "Igando/Ikotun", value: "Igando/Ikotun"},
  {label: "Igbogbo/Bayeku", value: "Igbogbo/Bayeku"},
  {label: "Ijede", value: "Ijede"},
  {label: "Ikeja", value: "Ikeja"},
  {label: "Ikorodu", value: "Ikorodu"},
  {label: "Ikorodu-North", value: "Ikorodu-North"},
  {label: "Ikorodu West", value: "Ikorodu West"},
  {label: "Ikosi Ejinrin", value: "Ikosi Ejinrin"},
  {label: "Ikosi/Isheri", value: "Ikosi/Isheri"},
  {label: "Ikoyi Obalende", value: "Ikoyi Obalende"},
  {label: "Imota", value: "Imota"},
  {label: "Iru-Victoria Island", value: "Iru-Victoria Island"},
  {label: "Isolo", value: "Isolo"},
  {label: "Itire/Ikate", value: "Itire/Ikate"},
  {label: "Kosofe", value: "Kosofe"},
  {label: "Lagos Island", value: "Lagos Island"},
  {label: "Lagos Island East", value: "Lagos Island East"},
  {label: "Lagos Mainland", value: "Lagos Island East"},
  {label: "Lekki", value: "Lekki"},
  {label: "Mosan/Okunnola", value: "Mosan/Okunnola"},
  {label: "Mushin", value: "Mushin"},
  {label: "Odi-Olowo/Ojuwoye", value: "Odi-Olowo/Ojuwoye"},
  {label: "Ojo", value: "Ojo"},
  {label: "Ojodu", value: "Ojodu"},
  {label: "Ojokoro", value: "Ojokoro"},
  {label: "Olorunda", value: "Olorunda"},
  {label: "Onigbongbo", value: "Onigbongbo"},
  {label: "Oriade", value: "Oriade"},
  {label: "Orile/Agege", value: "Orile/Agege"},
  {label: "Oshodi-Isolo", value: "Oshodi-Isolo"},
  {label: "Oto/Awori", value: "Oto/Awori"},
  {label: "Shomolu", value: "Shomolu"},
  {label: "Surulere", value: "Surulere"},
  {label: "Yaba", value: "Yaba"},
];
